CREATE PROCEDURE UpdateCarYear
@CARID INT,
@YEAR INT
AS
BEGIN
	UPDATE Autos
	SET Año = @YEAR WHERE AutoID = @CARID;
END

CREATE PROCEDURE CreateCar
@BRANCH VARCHAR(50),
@MODEL VARCHAR(50),
@YEAR INT,
@IDCHASSIS INT
AS
BEGIN
	INSERT INTO Autos VALUES
	( @BRANCH, @MODEL, @YEAR, @IDCHASSIS);
END

EXEC CreateCar @BRANCH = 'Subaru', @MODEL = 'NS-2017', @YEAR = 2017, @IDCHASSIS = 1;

CREATE PROCEDURE DeleteCar 
@ID INT
AS
BEGIN
DELETE FROM Autos WHERE AutoID=@ID;
END;



EXEC DeleteCar @ID = 98;


CREATE PROCEDURE GetAllCars AS
BEGIN
SELECT 
A.AutoID,
A.Marca,
A.Modelo,
A.Año,
TC.NombreChasis
FROM Autos AS A 
INNER JOIN TiposChasis AS TC 
ON A.ChasisID = TC.ChasisID;
END