/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package s19;


import dblogic.Car;
import java.awt.GridLayout;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JLabel;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Admin
 */
public class CarCRUD extends javax.swing.JFrame {
    private Car car;
    private DefaultTableModel tableModel = new DefaultTableModel();
    
    public CarCRUD(Connection dbConnection){
        this.car = new Car(dbConnection); // New Car object                                
        
        String ids[] = {"ID", "Marca", "Modelo", "Año", "Chasis"}; //Adding ids for table headers       
        this.tableModel.setColumnIdentifiers(ids); // Setting table headers
        
        initComponents();
        
        this.tCars.setModel(this.tableModel); // Settin table model
    }

    /**
     * Creates new form Autos
     */
    public CarCRUD() {        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tCars = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLoadCars = new javax.swing.JButton();
        btnAddCar = new javax.swing.JButton();
        btnUpdateCarYear = new javax.swing.JButton();
        btnDeleteCar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RUNNER S.A DE C.V.");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tCars.setBackground(new java.awt.Color(153, 153, 153));
        tCars.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tCars.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        tCars.setForeground(new java.awt.Color(255, 255, 255));
        tCars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tCars.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tCars.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tCars);

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("IMPORTADORA DE AUTOS - RUNNER S.A DE C.V.");

        jLabel2.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Autos");

        btnLoadCars.setText("Cargar datos");
        btnLoadCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadCarsActionPerformed(evt);
            }
        });

        btnAddCar.setBackground(new java.awt.Color(0, 153, 153));
        btnAddCar.setText("Agregar auto");
        btnAddCar.setToolTipText("Agrega un nuevo Auto a la base de datos");
        btnAddCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCarActionPerformed(evt);
            }
        });

        btnUpdateCarYear.setBackground(new java.awt.Color(204, 204, 0));
        btnUpdateCarYear.setText("Editar año");
        btnUpdateCarYear.setToolTipText("Edita el año del auto seleccionado de la tabla de registros");
        btnUpdateCarYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCarYearActionPerformed(evt);
            }
        });

        btnDeleteCar.setBackground(new java.awt.Color(255, 51, 0));
        btnDeleteCar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDeleteCar.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteCar.setText("Borrar regitro");
        btnDeleteCar.setToolTipText("Elimina el registro seleccionado de la tabla de autos en la base de datos");
        btnDeleteCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel2)
                        .addGap(48, 48, 48)
                        .addComponent(btnLoadCars)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btnAddCar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnUpdateCarYear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDeleteCar)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnLoadCars))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCar)
                    .addComponent(btnUpdateCarYear)
                    .addComponent(btnDeleteCar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadCarsActionPerformed
        // TODO add your handling code here:
        ResultSet carsData = this.car.getAllCars(); // Get cars data from a SP 
        try{
            if(carsData != null){ // Checks if there is data or not
                this.tableModel.setRowCount(0);
                while(carsData.next()){ // While there is rows to get
                    // Getting and saving fields from the row
                    int carID = carsData.getInt("AutoID");
                    String carBrand = carsData.getString("Marca");
                    String carModel = carsData.getString("Modelo");
                    int carYear = carsData.getInt("Año");
                    String carChassis = carsData.getString("NombreChasis");
                    // Adding fields to a new row in the table model
                    this.tableModel.addRow(new Object[] {carID, carBrand, carModel, carYear, carChassis});                    
                }                
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Algo salió mal al mostrar los autos", "Error", JOptionPane.ERROR_MESSAGE);            
        }finally{
            try{
                if(carsData != null) carsData.close();
            }catch(SQLException e){
                System.out.println(e.getMessage());                
            }
        }
        
    }//GEN-LAST:event_btnLoadCarsActionPerformed

    private void btnAddCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCarActionPerformed
        // TODO add your handling code here:
        
        JPanel formPanel = new JPanel(new GridLayout(5,2,5,5)); // Form grid
        // Creating controls for formPanel
        JLabel labelBranch = new JLabel("Marca");
        JTextField textBranch = new JTextField();
        JLabel labelModel = new JLabel("Modelo");
        JTextField textModel = new JTextField();
        JLabel labelYear = new JLabel("Año");
        JTextField textYear = new JTextField();
        JLabel labelChassisID = new JLabel("Chassis ID");
        JTextField textChassisID = new JTextField();
        // Adding controls to formPanel
        formPanel.add(labelBranch);
        formPanel.add(textBranch);
        formPanel.add(labelModel);
        formPanel.add(textModel);
        formPanel.add(labelYear);
        formPanel.add(textYear);
        formPanel.add(labelChassisID);
        formPanel.add(textChassisID);
        
        // Showing formPanel
        int result = JOptionPane.showConfirmDialog(this, formPanel, "Agregar registro", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        
        // Getting formPanel data
        if(result == JOptionPane.OK_OPTION){
            String branch = textBranch.getText();
            String model = textModel.getText();
            int year = Integer.parseInt( textYear.getText() ); // Converting to int 
            int chassisID = Integer.parseInt( textChassisID.getText() ); // Converting to int
            if(this.car.addNewCar(branch, model, year, chassisID)){
                JOptionPane.showMessageDialog(this, "Se ha agregado el registro correcatamente");                
                this.btnLoadCarsActionPerformed(null);
            } else JOptionPane.showMessageDialog(this, "No se pudo agregar el registro, intentelo más tarde.");
        }
    }//GEN-LAST:event_btnAddCarActionPerformed

    private void btnUpdateCarYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCarYearActionPerformed
        // TODO add your handling code here:
        int selectedRow = this.tCars.getSelectedRow(); // Gettin the current row selected
        if ( selectedRow == -1) JOptionPane.showMessageDialog(this, "Por favor, selecciona un registro de la tabla");
        else{
            int carID = (int) this.tCars.getValueAt(selectedRow, 0);// Gettin ID from row selected
            int carYear = (int) this.tCars.getValueAt(selectedRow, 3); // Getting year from row selected
            // Creting form to update record
            JPanel formPanel = new JPanel(new GridLayout(1, 2));
            formPanel.add(new JLabel("Año"));
            JTextField textYear = new JTextField();
            textYear.setText(String.valueOf(carYear));
            formPanel.add(textYear);
            // Showing panel
            int result = JOptionPane.showConfirmDialog(this,formPanel,"Editar Año del auto", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);            
            if (result == JOptionPane.OK_OPTION){
                String newYearInput = textYear.getText();
                try{
                    carYear = Integer.parseInt(newYearInput);
                }catch(NumberFormatException e) {
                    JOptionPane.showMessageDialog(this,"Año incorrecto. Por favor ingresa un año válido, ej: 2025","Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }                
                
                if( this.car.updateCarYear(carID, carYear)){
                    this.btnLoadCarsActionPerformed(null);
                    JOptionPane.showMessageDialog(this, "Se ha actualizado el año correcatamente");
                }
                else JOptionPane.showMessageDialog(this, "No se pudo actualizar, intentelo más tarde.");
            }
        }
    }//GEN-LAST:event_btnUpdateCarYearActionPerformed

    private void btnDeleteCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCarActionPerformed
        // TODO add your handling code here:
        int selectedRow = this.tCars.getSelectedRow(); // Gettin the current row selected
        if ( selectedRow == -1) JOptionPane.showMessageDialog(this, "Por favor, selecciona un registro de la tabla");
        else{
            int carID = (int) this.tCars.getValueAt(selectedRow, 0); // Getting id of the record to delete
            int result = JOptionPane.showConfirmDialog(this,"¿Estás seguro de querer borrar el registro con ID:" + carID,"Borrar auto", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);            
            if (result == JOptionPane.OK_OPTION){
                if(this.car.deleteCar(carID)){
                    this.btnLoadCarsActionPerformed(null);
                    JOptionPane.showMessageDialog(this, "El registro con ID: " + carID + " fue eliminado correctamente." );
                }
            }
            
        }
    }//GEN-LAST:event_btnDeleteCarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarCRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCar;
    private javax.swing.JButton btnDeleteCar;
    private javax.swing.JButton btnLoadCars;
    private javax.swing.JButton btnUpdateCarYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tCars;
    // End of variables declaration//GEN-END:variables
}
